In [1]:
import numpy as np 

In [2]:
A = np.array([[1,2], [3,2]])
b = np.array([-2,6])

np.linalg.solve(A, b)

array([ 4., -3.])

In [3]:
A = np.array([[2,4], [3,3]])
b = np.array([22,15])

np.linalg.solve(A, b)

array([-1.,  6.])

In [5]:
A = np.array([[1,-3,-6], [0, 1, 2], [-4,12,21]])
b  = np.array([4, -2, -4])
np.linalg.solve(A, b)

array([-2.,  6., -4.])

In [6]:
A = np.array([
    [0, 2, 4],
    [1, 3, 3],
    [2, 7, 6]
])
b = np.array([4, 5, 10])

np.linalg.solve(A, b)

array([2., 0., 1.])

In [7]:
A = np.array([
    [3, 12, 42],
    [1, 2, 8],
    [2, 5, 16]
])

b = np.array([-27, -5, -6])

np.linalg.solve(A, b)

array([ 3.,  4., -2.])

In [8]:
A = np.array([
    [4, 8, 4],
    [4, 6, 0],
    [3, 3, -1]
])

b = np.array([20, 4, 1])

np.linalg.solve(A, b)

array([ 4., -2.,  5.])

In [9]:
A = np.array([
    [2, -8, 0],
    [-7, 2, -5],
    [3, 0, 2]
])
b = np.array([18, -6, 1])

np.linalg.solve(A, b)

array([ 1., -2., -1.])

In [10]:
A = np.array([
    [-1, 3, -5, -8],
    [4, -8, 4, 4],
    [3, 5, -16, 1],
    [-1, 1, -3, -1]]
)
b = np.array([2, -44, 18, 6])

np.linalg.solve(A, b)

array([-3.00000000e+00,  5.00000000e+00, -1.34039121e-16,  2.00000000e+00])

In [12]:
A = np.array([
    [-1, 6, 4, 0],
    [4, -22, -2, 2],
    [1, -6, -5, 3],
    [0, -3, -22, 0]
])
b = np.array([-22, 0, 5, 6])
np.linalg.solve(A, b)

array([ 1.17814166e+18,  2.15992638e+17, -2.94535416e+16, -9.81784719e+15])

In [13]:
A = np.array([
    [2, 2, -8],
    [-3, -5, 6],
    [5, -1, -38]
])
b = np.array([4, -4, 16])
np.linalg.solve(A, b)

LinAlgError: Singular matrix

In [14]:
A = np.array([
    [1, 1, -1, 2],
    [4, 2, -6, 2],
    [-3, 1, 7, 6],
    [-1, -1, 4, 3] 
])
b = np.array([7, 16, 3, 8])
np.linalg.solve(A, b)

LinAlgError: Singular matrix

In [15]:
A = np.array([
    [7, 2, -4],
    [-5, 10, 3]
    
])
B = np.array([
    [7, 1],
    [7, 2],
    [-2, 6]
])

A@B 

array([[ 71, -13],
       [ 29,  33]])

In [16]:
A = np.array([
    [3, -1],
    [1, 4]
])
B = np.array([
    [5, 2],
    [-2, 3]
])
C = np.array([
    [2, 0],
    [6, 2]
])
AB = A @ B 
AC = A @ C 
AB + AC

array([[17,  1],
       [23, 22]])

In [18]:
from sympy import Matrix, symbols, Eq, solve
m = Matrix("1 2 3; 0 1 4; 5 6 0")
print(m)

TypeError: 
Data type not understood; expecting list of lists or lists of values.