In [1]:
import numpy as np 

In [2]:
A = np.array([[1,2], [3,2]])
b = np.array([-2,6])

np.linalg.solve(A, b)

array([ 4., -3.])

In [3]:
A = np.array([[2,4], [3,3]])
b = np.array([22,15])

np.linalg.solve(A, b)

array([-1.,  6.])

In [5]:
A = np.array([[1,-3,-6], [0, 1, 2], [-4,12,21]])
b  = np.array([4, -2, -4])
np.linalg.solve(A, b)

array([-2.,  6., -4.])

In [6]:
A = np.array([
    [0, 2, 4],
    [1, 3, 3],
    [2, 7, 6]
])
b = np.array([4, 5, 10])

np.linalg.solve(A, b)

array([2., 0., 1.])

In [7]:
A = np.array([
    [3, 12, 42],
    [1, 2, 8],
    [2, 5, 16]
])

b = np.array([-27, -5, -6])

np.linalg.solve(A, b)

array([ 3.,  4., -2.])

In [8]:
A = np.array([
    [4, 8, 4],
    [4, 6, 0],
    [3, 3, -1]
])

b = np.array([20, 4, 1])

np.linalg.solve(A, b)

array([ 4., -2.,  5.])