In [1]:
import numpy as np 

In [3]:
A = np.array([
    [7, 6],
    [17, 9]
])
B = np.array([
    [0, 8],
    [-2, 5]
])
A + B 

array([[ 7, 14],
       [15, 14]])

In [4]:
A = np.array([
    [1, -5, 7],
    [-3, 2, 8]
])

A + (-1 * A)

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
A = np.array([
    [5, -1],
    [0, 11],
    [7, -2]
])
B = np.array([
    [6, 1, 8],
    [-3, 0, 4]
])
A.dot(B)  # matrix multiplication

array([[ 33,   5,  36],
       [-33,   0,  44],
       [ 48,   7,  48]])

In [6]:
A = np.array([
    [-3, 6],
    [1, 2]
])

# get inverse of A
A_inv = np.linalg.inv(A)
A_inv

array([[-0.16666667,  0.5       ],
       [ 0.08333333,  0.25      ]])

In [7]:
A = np.array([
    [1, 0, 0],
    [3, 1, -4],
    [-2, -1, 5]
])
np.linalg.inv(A)

array([[ 1.,  0.,  0.],
       [-7.,  5.,  4.],
       [-1.,  1.,  1.]])

In [8]:
np.linalg.inv(np.array([
    [1, 0, -5],
    [3, 2, -9],
    [1, -2, -10]
]))

array([[-19. ,   5. ,   5. ],
       [ 10.5,  -2.5,  -3. ],
       [ -4. ,   1. ,   1. ]])